name: quote
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.0
  get_it: ^7.6.0
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  http: ^1.1.2
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.1
  shake: ^2.2.0
  carousel_slider: ^4.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  flutter_gen_runner:
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

flutter_gen:
  assets:
    enabled: true
    outputs:
      class_name: Assets
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true